name: "Lint PR title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types:
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
            BREAKING

          scopes:
            vuln
            misconf
            secret
            license

            image
            fs
            repo
            sbom
            server
            k8s

            alpine
            redhat
            alma
            rocky
            mariner
            oracle
            debian
            ubuntu
            amazon
            suse
            photon
            distroless

            ruby
            php
            python
            nodejs
            rust
            dotnet
            java
            go
            c
            c++
            
            os
            lang

            kubernetes
            dockerfile
            terraform
            cloudformation

            docker
            podman
            containerd
            oci

            cli
            flag
            
            cyclonedx
            spdx

            helm
            report
            db
            deps